uint8 Veh_fb_FaultLevel
bool Veh_fb_AutoSpdCANCtrlCmd
bool Veh_fb_AutoIOCANCmd
bool Veh_fb_RemoteTrqCANCtrlCmd
bool Veh_fb_AutoTrqCANCtrlCmd

bool Veh_fb_EPSDisOnline
bool Veh_fb_EPSfault
bool Veh_fb_EPSMosfetOT
bool Veh_fb_EPSWarning
bool Veh_fb_EPSDisWork
bool Veh_fb_EPSOverCurrent

uint16 Veh_fb_EHBMCUFaultFb

uint16 Veh_fb_DrvMCUFaultFb

bool Veh_fb_AUXBMSDisOnline

bool Veh_fb_AuxScram

bool Veh_fb_AuxRemoteClose

bool Veh_fb_AuxRemoteDisOnline

uint8 Veh_fb_AuxReserve

